# Generated by Django 4.2.16 on 2026-07-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
